### ISSUE TITLE
Unable to get the states property to work

### ISSUE THREAD

**Issue by Shazuli** [jbredwards/Fluidlogged-API#136]
**Describe the bug**
I'm trying to only allowing half-blocks from Storage Drawers to be fluidloggable:
![image](https://user-images.githubusercontent.com/9884180/205336119-1b4df0d6-526e-4ea9-9b93-1296786b8b0d.png)
![image](https://user-images.githubusercontent.com/9884180/205336241-b34e666f-3187-4bc2-b212-afb06c12888a.png)

```cfg
whitelist:[
	{blockId: "storagedrawers:basicdrawers", states: [{block: "half2"},{block: "half4"}]}
]
```

But putting in those options and reloading causes this to show up:
`An unknown error occurred while attempting to perform this command`

However, if the blockstate property doesn't exist it will say it reloaded successfully but with no changes obviously.

```cfg
whitelist:[
	{blockId: "storagedrawers:basicdrawers", states: [{block: "half9"},{differentprop: "half4"}]}
]
```

Tried this with another mod with the same results:

```cfg
whitelist:[
	{blockId: "quark:stone_speleothem", states: [{size: "big"}]}
]
```

**Logs**
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_311]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_311]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$ConfigPredicateBuilder.lambda$gatherStatesMetadata$1(ConfigHandler.java:365) ~[ConfigHandler$ConfigPredicateBuilder.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_311]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$ConfigPredicateBuilder.gatherStatesMetadata(ConfigHandler.java:362) ~[ConfigHandler$ConfigPredicateBuilder.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$ConfigPredicateBuilder.build(ConfigHandler.java:333) ~[ConfigHandler$ConfigPredicateBuilder.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler.readPredicates(ConfigHandler.java:204) ~[ConfigHandler.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler.complete(ConfigHandler.java:172) ~[ConfigHandler.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.command.CommandReloadConfig.execute(CommandReloadConfig.java:40) ~[CommandReloadConfig.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
```

**Additional context**
* Fluidlogged: v1.9.0.3-mc1.12.2
* [Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/storage-drawers): 1.12.2-5.4.0
* [Quark](https://www.curseforge.com/minecraft/mc-mods/quark): r1.6-179 (r1.6-179)

**Comment by jbredwards** [comment]
fixed in v1.9.0.4
