### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Nianor** [jbredwards/Fluidlogged-API#14]
Any time I load a world with versions 1.4.1 or 1.4.2, I get an instant crash with the following error:
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$Anonymous$eb5c0bdd60f5450ca4026c2da83a2525
	at net.minecraft.world.World.<init>(World.java:126)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:110)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:121)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
	
The issue vanishes when I run 1.4, and while I can share my modlist, it's a pretty long one, so I'd rather not do so unless you need it.

**Comment by jbredwards** [comment]
fixed in v1.5!
