### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by liopard** [jbredwards/Fluidlogged-API#16]
fluidlogged_api_v1.4.2_mc1.12.2.jar

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_175625_s(World.java:2387)
	at git.jbredwards.fluidlogged_api.util.FluidloggedUtils.getStored(FluidloggedUtils.java:41)
	at git.jbredwards.fluidlogged_api.common.event.FluidloggedEvents.showAdditionalDebugData(FluidloggedEvents.java:140)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_46_FluidloggedEvents_showAdditionalDebugData_Text.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1421)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jbredwards** [comment]
fixed in v1.4.3!
