### ISSUE TITLE
Quark compatibility?

### ISSUE THREAD

**Issue by liopard** [jbredwards/Fluidlogged-API#20]
Fluidlogged-API-v1.4.4-mc1.12.2.jar
// ----------
[16:58:59] [Client thread/INFO] [Quark ASM]: Located patch target node INVOKESPECIAL net/minecraft/block/state/BlockPistonStructureHelper.<init> (Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;Z)V
[16:58:59] [Client thread/INFO] [Quark ASM]: Patch result: true
[16:58:59] [Client thread/INFO] [Quark ASM]: Applying Transformation to method (Names [checkForMove, func_176316_e] Descriptor (Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;)V)
[16:58:59] [Client thread/INFO] [Quark ASM]: Located Method, patching...
[16:58:59] [Client thread/INFO] [Quark ASM]: Located patch target node INVOKESPECIAL net/minecraft/block/state/BlockPistonStructureHelper.<init> (Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;Z)V
[16:58:59] [Client thread/INFO] [Quark ASM]: Patch result: true
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: java.lang.ExceptionInInitializerError
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraftforge.common.ForgeHooks.<clinit>(ForgeHooks.java:339)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName0(Native Method)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.Class.forName(Unknown Source)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.getTargetClass(ReflectorClass.java:47)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:26)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.ReflectorClass.<init>(ReflectorClass.java:17)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:261)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.state.BlockStateContainer$Builder.build(BlockStateContainer.java:584)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at git.jbredwards.fluidlogged_api.asm.swapper.BlockLiquidBase.func_180661_e(BlockLiquidBase.java:44)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.Block.<init>(Block.java:234)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.Block.<init>(Block.java:243)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.BlockLiquid.<init>(BlockLiquid.java:37)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at git.jbredwards.fluidlogged_api.asm.swapper.BlockLiquidBase.<init>(BlockLiquidBase.java:39)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.BlockDynamicLiquid.<init>(BlockDynamicLiquid.java:19)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.block.Block.func_149671_p(Block.java:2349)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:59:00] [Client thread/INFO] [STDERR]: [net.optifine.reflect.ReflectorClass:getTargetClass:55]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:59:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalStateException: Invalid Item requested: air
[16:59:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.init.Items.func_179554_a(SourceFile:228)
[16:59:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.init.Items.<clinit>(SourceFile:13)
[16:59:00] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 24 more

**Comment by jbredwards** [comment]
When I use quark with my mod, it doesn't crash. Perhaps this is fixed in v1.5? If not let me know

**Comment by jbredwards** [comment]
marking this as closed until further notice
