### ISSUE TITLE
Performant incompatibility (server side)

### ISSUE THREAD

**Issue by Druwan-ctrl** [jbredwards/Fluidlogged-API#26]
This is the crash log when trying to load performant:

Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$Anonymous$470a8cadb93d44d08c66f00809298f15
	at net.minecraft.world.World.<init>(World.java:126)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:110)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:873)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:840)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4390)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World$Anonymous$470a8cadb93d44d08c66f00809298f15
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer git.jbredwards.fluidlogged_api.asm.swapper.ASMSwapper@3c232051 from coremod Fluidlogged Plugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more
Caused by: java.lang.NullPointerException

LTM if there's any info I should provide or if it's already clear

**Comment by jbredwards** [comment]
can you send the full log?

**Comment by Druwan-ctrl** [comment]
Sorry for the late reply, please give me some time as i cannot do tests on the server right now

**Comment by jbredwards** [comment]
closed due to inactivity, but the class seeming to cause the crash has been removed, so probably fixed
