### ISSUE TITLE
Futuremc bug?

### ISSUE THREAD

**Issue by Carvercarver1** [jbredwards/Fluidlogged-API#50]
```
Description: Initializing game

java.lang.NoClassDefFoundError: thedarkcolour/futuremc/block/villagepillage/LanternBlock
    at thedarkcolour.futuremc.registry.FBlocks.<clinit>(FBlocks.kt:31)
    at thedarkcolour.futuremc.registry.RegistryEventHandler.onBlockRegistry(RegistryEventHandler.kt:46)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_RegistryEventHandler_onBlockRegistry_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thedarkcolour.futuremc.block.villagepillage.LanternBlock
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
Caused by: java.lang.NoClassDefFoundError: git/jbredwards/fluidlogged_api/common/block/IFluidloggable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: git.jbredwards.fluidlogged_api.common.block.IFluidloggable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 24 more
Caused by: java.lang.NullPointerException
```

Also, if I try to insert futuremc lantern into the blacklist config, it straight up won't even start the game. Might be this:
```

Unable to launch
com.google.gson.JsonParseException: net.minecraft.nbt.NBTException: Expected '{' but got '"' at: "<--[HERE]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$Deserializer.deserialize(ConfigHandler.java:272) ~[ConfigHandler$Deserializer.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$Deserializer.deserialize(ConfigHandler.java:241) ~[ConfigHandler$Deserializer.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler.init(ConfigHandler.java:111) ~[ConfigHandler.class:?]
	at git.jbredwards.fluidlogged_api.mod.asm.ASMHandler.injectData(ASMHandler.java:70) ~[Fluidlogged-API-v1.7-mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:151) ~[forge-1.12.2-14.23.5.2859.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraft.nbt.NBTException: Expected '{' but got '"' at: "<--[HERE]
	at net.minecraft.nbt.JsonToNBT.func_193604_b(SourceFile:315) ~[gp.class:?]
	at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:177) ~[gp.class:?]
	at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:34) ~[gp.class:?]
	at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:29) ~[gp.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler$Deserializer.deserialize(ConfigHandler.java:247) ~[ConfigHandler$Deserializer.class:?]
	... 15 more
```

Then, there is this: 

```
[20:08:54] [main/ERROR] [LaunchWrapper]: Unable to launch
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 24 column 14 path $.blacklist
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[Gson.class:?]
	at git.jbredwards.fluidlogged_api.mod.common.config.ConfigHandler.init(ConfigHandler.java:111) ~[ConfigHandler.class:?]
	at git.jbredwards.fluidlogged_api.mod.asm.ASMHandler.injectData(ASMHandler.java:70) ~[Fluidlogged-API-v1.7-mc1.12.2.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:151) ~[forge-1.12.2-14.23.5.2859.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 24 column 14 path $.blacklist
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	... 9 more

```

Seems to work, if futuremc is removed.

**Comment by jbredwards** [comment]
This is a problem with FutureMC

**Comment by Carvercarver1** [comment]
Will relay, thanks.

**Comment by Carvercarver1** [comment]
If anything, is it caused by the registering issue or something entirely else? Perhaps I am not inputting the values in the config right.

**Comment by Carvercarver1** [comment]
For example, what I tried inserting is:
[futuremc:lantern] [blocklantern], which... I don't think is right.

**Comment by jbredwards** [comment]
It's not a problem with anything you're doing. FutureMC uses classes from v1.6.2 of this mod, it has yet to add support for the newest version

**Comment by jbredwards** [comment]
> For example, what I tried inserting is: [futuremc:lantern] [blocklantern], which... I don't think is right.

here's an example I created for someone else not sure about the config format:
```
"whitelist":[
    {blockId, validMeta(optional, if not present all are valid), validFluidNames(optional, if not present all are valid)},
    #examples
    {"blockId":"minecraft:bedrock"},
    {"blockId":"minecraft:oak_stairs", validMeta:[0, 3, 8]},
    {"blockId":"minecraft:enchanting_table",validFluidNames:["lava"]}
]
```

**Comment by Carvercarver1** [comment]
Oh, thanks! For a while, what I can use for a substitute?

**Comment by Carvercarver1** [comment]
If anything, is there a way to disable the logging for the futuremc mod as a whole completely? Not sure if that is an option, though. Unless it is a specific conflict which config meddling can't fix

**Comment by jbredwards** [comment]
The two things you can do in the meantime are either use v1.6.2 of Fluidlogged API, or fork FutureMC and update the classes yourself for private use. Not sure there's anything you can do outside that besides wait for the fix.
